"""empty message

Revision ID: 78947d0c75a8
Revises: 6e834b3c6fe7
Create Date: 2025-08-29 09:59:52.468248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78947d0c75a8'
down_revision = '6e834b3c6fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
