"""empty message

Revision ID: bcd5faadfbb6
Revises: 
Create Date: 2025-10-01 06:11:30.988553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd5faadfbb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.String(length=10), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('background',
    sa.Column('background_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('introduction', sa.String(length=255), nullable=False),
    sa.Column('abilities_score_description', sa.Text(), nullable=True),
    sa.Column('feats_description', sa.Text(), nullable=True),
    sa.Column('skill_proficiencies_description', sa.Text(), nullable=True),
    sa.Column('tool_proficiencies_description', sa.Text(), nullable=True),
    sa.Column('languages_description', sa.Text(), nullable=True),
    sa.Column('equipment_description', sa.Text(), nullable=True),
    sa.Column('specific_table_name', sa.String(length=255), nullable=True),
    sa.Column('specific_tabla_desc', sa.Text(), nullable=True),
    sa.Column('feature', sa.String(length=255), nullable=True),
    sa.Column('feature_desc', sa.Text(), nullable=True),
    sa.Column('variant', sa.String(length=255), nullable=True),
    sa.Column('variant_desc', sa.Text(), nullable=True),
    sa.Column('variant_feature', sa.String(length=255), nullable=True),
    sa.Column('variant_feature_desc', sa.Text(), nullable=True),
    sa.Column('suggested_characteristics', sa.Text(), nullable=True),
    sa.Column('spell_list_introduction', sa.Text(), nullable=True),
    sa.Column('spell_list_extended', sa.Text(), nullable=True),
    sa.Column('contacts_list', sa.Text(), nullable=True),
    sa.Column('background_tags', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('background_id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('setting', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('class_name', sa.String(length=120), nullable=False),
    sa.Column('race_name', sa.String(length=120), nullable=False),
    sa.Column('background_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feats',
    sa.Column('feats_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.String(length=255), nullable=True),
    sa.Column('feats_tags', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('feats_id')
    )
    op.create_table('magics_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('base_item_type', sa.String(length=50), nullable=False),
    sa.Column('attunement_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('magic_item_type', sa.String(length=50), nullable=True),
    sa.Column('base_armor', sa.String(length=50), nullable=True),
    sa.Column('dex_bonus', sa.String(length=20), nullable=True),
    sa.Column('str_requirement', sa.String(length=20), nullable=True),
    sa.Column('stealth_check', sa.String(length=50), nullable=True),
    sa.Column('base_weapon', sa.String(length=50), nullable=True),
    sa.Column('requires_attunement', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('subtype', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=120), nullable=False),
    sa.Column('challenge', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specie',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=False),
    sa.Column('speed_walking', sa.Text(), nullable=True),
    sa.Column('speed_burrowing', sa.Text(), nullable=True),
    sa.Column('speed_flying', sa.Text(), nullable=True),
    sa.Column('speed_swimming', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('hide_trait', sa.Text(), nullable=True),
    sa.Column('specie_trait', sa.String(length=255), nullable=False),
    sa.Column('will_have_species', sa.String(length=255), nullable=True),
    sa.Column('large_avatar', sa.String(length=255), nullable=True),
    sa.Column('portrait_avatar', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('specie_id')
    )
    op.create_table('spell',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('spell_name', sa.String(length=255), nullable=False),
    sa.Column('spell_level', sa.String(length=255), nullable=False),
    sa.Column('spell_school', sa.String(length=255), nullable=False),
    sa.Column('casting_time', sa.String(length=255), nullable=False),
    sa.Column('casting_time_select', sa.String(length=255), nullable=True),
    sa.Column('reaction_casting_time', sa.String(length=255), nullable=False),
    sa.Column('components', sa.Boolean(), nullable=True),
    sa.Column('material_components', sa.String(length=255), nullable=False),
    sa.Column('spell_range', sa.String(length=255), nullable=False),
    sa.Column('range_distance', sa.String(length=255), nullable=False),
    sa.Column('duration_type', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=255), nullable=False),
    sa.Column('duration_select', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('ritual_spell', sa.Boolean(), nullable=True),
    sa.Column('at_higher_levels', sa.Boolean(), nullable=True),
    sa.Column('higher_level_scaling', sa.String(length=255), nullable=False),
    sa.Column('available_for_classes', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('spell_id')
    )
    op.create_table('subclasses',
    sa.Column('subclasses_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('spellcasting_ability', sa.String(length=255), nullable=True),
    sa.Column('can_cast_spells', sa.String(length=255), nullable=True),
    sa.Column('additional_spell_list', sa.String(length=255), nullable=True),
    sa.Column('spell_prepare_type', sa.String(length=255), nullable=True),
    sa.Column('knows_all_spells', sa.String(length=255), nullable=True),
    sa.Column('spell_learning_style', sa.String(length=255), nullable=True),
    sa.Column('additional_specific_spells', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('large_avatar', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('subclasses_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subclasses')
    op.drop_table('spell')
    op.drop_table('specie')
    op.drop_table('monster')
    op.drop_table('magics_items')
    op.drop_table('feats')
    op.drop_table('character')
    op.drop_table('campaign')
    op.drop_table('background')
    op.drop_table('user')
    # ### end Alembic commands ###
